core/urls.py
from django.urls import path
from .views import index
from django.conf import settings
from django.conf.urls.static import static

app_name = "core"
urlpatterns = [
    path("", index, name = "index"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food_forest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls"))
]

core/models.py
from enum import unique
from django.db import models

class Food(models.Model):
    name = models.CharField(max_length = 250, unique = True)
    slug = models.SlugField(max_length = 250, unique = True)

    def __str__(self):
        return self.name

class Ingredient(models.Model):
    name = models.CharField(max_length = 250, unique = True)
    slug = models.SlugField(max_length = 250, unique = True)
    quantity = models.IntegerField(default = 0)
    calories = models.FloatField(default = 0.0)

    def __str__(self):
        return self.name

    def get_calories_per_quantity(self):
        if self.quantity == 0:
            return 0.0

        return self.calories / self.quantity

class Recipe(models.Model):
    food = models.ForeignKey(Food, on_delete = models.CASCADE, related_name = "recipes")
    ingredients = models.ManyToManyField(Ingredient)

    def get_ingredients(self):
        return ", ".join([x.name for x in self.ingredients.all()])

    def __str__(self):
        return f"{self.food.name} > {self.get_ingredients()}"

core/views.py
import os
import h5py
import numpy as np
from PIL import Image
import tensorflow as tf
from secrets import token_hex
from django.conf import settings
from django.shortcuts import render
from .models import Food, Ingredient, Recipe
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage

DATASET = settings.DATASET
MODEL = settings.MODEL

def predict(images):
    """
    A function to get labels for input images using a trained model
    """
    file = h5py.File(DATASET, "r")
    model = tf.keras.models.load_model(MODEL)
    predictions = model.predict(images)
    argmaxs = np.argmax(predictions, axis = 1)
    labels = []
    
    for x in argmaxs:
        labels.append(file["category_names"][x].decode('ascii'))

    return labels

def get_recipe_data(labels, urls):
    recipes = []

    for label, url in zip(labels, urls):
        new_label = " ".join(label.lower().split("_"))
        food = Food.objects.filter(name = new_label)

        if not food.exists():
            continue
        
        food = food.first()
        recipe = food.recipes.all().order_by("?").first()
        ingredients = recipe.ingredients.all()
        recipes.append((recipe, ingredients, url))

    return recipes

def load_images(paths):
    finals = []

    for path in paths:
        image = Image.open(path)
        image = np.asarray(image)
        finals.append(image)
        
    return np.array(finals)

def index(request):
    """
    View for home or index page
    """
    images = []
    recipes = []
    paths = []
    urls = []

    if request.method == "POST":
        images = request.FILES.getlist("images")

        for image in images:
            path = default_storage.save(f"{token_hex(16)}.png", ContentFile(image.read()))
            urls.append(settings.MEDIA_URL + path)
            paths.append(os.path.join(settings.MEDIA_ROOT, path))

        images = load_images(paths)
        images = np.array(images)
        labels = predict(images)
        recipes = get_recipe_data(labels, urls)

    return render(request, "core/index.html", {
        "images": images,
        "recipes": recipes
    })

core/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Food Forest | {% block title %}{% endblock %}</title>
  <link rel="icon" type="image/x-icon" href="{% static 'core/images/logo.ico' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <style>
    .bg-white {
      background-color: #FFFFFF;
    }

    .logo {
      height: 50px;
    }
    
    .w-custom {
      width: 150px !important;
      height: 150px !important;
    }

    .m-custom {
      margin: 2px !important;
    }

    .nm-custom {
      margin: -2px !important;
    }
  </style>
  {% block head %}
  {% endblock %}
</head>
<body class="bg-dark">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container d-flex align-items-center justify-content-between">
      <div>
        <img src="{% static 'core/images/logo.png' %}" class="logo me-2" alt="">
      </div>
      <div class="d-flex text-dark">
        <a class="nav-link text-dark pe-1" aria-current="page" href="{% url 'core:index' %}">Home</a>
        <a class="nav-link text-dark pe-1" aria-current="page" href="https://github.com/ItsMrVaibhav/Food-Forest" target="_blank">GitHub Repository</a>
      </div>
    </div>
  </nav>
  <div class="container p-0">
    {% block body %}
    {% endblock %}
  </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
{% block javascript %}
{% endblock %}
</html>

core/templates/core/index.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}
Home
{% endblock %}

{% block head %}
{% endblock %}

{% block body %}
<form action="{% url 'core:index' %}" class="p-3 bg-white" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="input-group">
    <span class="input-group-text">Images</span>
    <input type="file" class="form-control" accept=".png" name="images" multiple>
    <input type="submit" value="Analyse" class="btn btn-dark">
  </div>
</form>
<div class="recipes" id="recipes">
  {% if recipes %}
    {% for recipe, ingredients, url in recipes %}
      <div class="card mt-3 bg-light rounded-0 border-0">
        <div class="card-body d-flex">
          <div class="d-flex flex-column align-items-center me-3 w-custom">
            <img src="{{ url }}" alt="Food Image" class="w-custom border border-dark rounded-0">
            <p class="mt-1 btn btn-sm btn-dark d-block w-100 rounded-0">{{ recipe.food.name|upper }}</p>
            <div class="d-flex flex-wrap nm-custom justify-content-center">
              {% for ingredient in ingredients %}
                <span class="badge text-dark bg-white m-custom border">{{ ingredient.name }}</span>
              {% endfor %}
            </div>
          </div>
          <div class="w-100 bg-white p-3">
            <h3>Nutritional Details</h3>
            <p>Following are the nutritional detals for each ingredient of the recipe.</p>
            <table class="table text-center table-sm mb-0 mt-3">
              <thead>
                <tr>
                  <th>S. No</th>
                  <th>Ingredient</th>
                  <th>Quantity (g)</th>
                  <th>Calories (kcal)</th>
                  <th>Calories per Gram (kcal/g)</th>
                </tr>
              </thead>
              <tbody>
                {% for ingredient in ingredients %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ ingredient.name|upper }}</td>
                  <td>{{ ingredient.quantity }} g</td>
                  <td>{{ ingredient.calories }} kcal</td>
                  <td>{{ ingredient.get_calories_per_quantity }} kcal/g</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    {% endfor %}
  {% endif %}
</div>
{% endblock %}

{% block javascript %}
{% endblock %}